## port number ##
server:
  port: 2121
  
## Database Driver Setup ##    
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mohan
    username: root
    password: root

## Hibernate Config ##   
  jpa:
    show-sql:  true
    hibernate:
      ddl-auto: update   
    database-platform: org.hibernate.dialect.MySQL5Dialect
